### ISSUE TITLE
s:if directive on img resulting to error 

### ISSUE THREAD

**Issue by tiaochuan** [eavichay/slimjs-docs#2]
I tried to do 
`<div s:if=“url”>
      <img bind:src=“url” />
</div>`
If “url” is null, I’m getting an error “http://locahost/null”. 
Looks like the img is still inserted into the document before removing it?

**Comment by eavichay** [comment]
Yes, all elements are inserted into a real DOM and not saved as template. Slim component does not render inner content while inside a `s:if`. You may want to create a simple Slim element that simply shows IMG inside, no need for shadow DOM.

```javascript
Slim.tag('s-img', '<img bind:src="src">', class extends Slim {});
```

In you template use
```html
<s-img s:if="myBoolean" bind:src="whatever"></s-img>
```

Please let me know if that works for you.

**Comment by tiaochuan** [comment]
Works well! Thanks! :)
